// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct StoreGenerated: Codable {
    public var pets: [PetGenerated]

    public init(pets: [PetGenerated]) {
        self.pets = pets
    }
}
