// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct C: Codable {
    public var kind: String

    public init(kind: String) {
        self.kind = kind
    }
}
