// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

public struct Order: Codable {
    public var id: Int?
    public var petID: Int?
    public var quantity: Int?
    public var shipDate: Date?
    /// Order Status
    public var status: String?
    public var isComplete: Bool

    public init(id: Int? = nil, petID: Int? = nil, quantity: Int? = nil, shipDate: Date? = nil, status: String? = nil, isComplete: Bool? = nil) {
        self.id = id
        self.petID = petID
        self.quantity = quantity
        self.shipDate = shipDate
        self.status = status
        self.isComplete = isComplete ?? false
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case petID = "petId"
        case quantity
        case shipDate
        case status
        case isComplete = "complete"
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try values.decodeIfPresent(Int.self, forKey: .id)
        self.petID = try values.decodeIfPresent(Int.self, forKey: .petID)
        self.quantity = try values.decodeIfPresent(Int.self, forKey: .quantity)
        self.shipDate = try values.decodeIfPresent(Date.self, forKey: .shipDate)
        self.status = try values.decodeIfPresent(String.self, forKey: .status)
        self.isComplete = try values.decodeIfPresent(Bool.self, forKey: .isComplete) ?? false
    }
}
