// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.User {
    var login: Login {
        Login(path: path + "/login")
    }

    struct Login {
        /// Path: `/user/login`
        let path: String

        /// Logs user into the system
        func get(username: String, password: String) -> Request<String> {
            Request(method: "GET", url: path, query: [("username", username), ("password", password)], id: "loginUser")
        }

        enum GetResponseHeaders {
            /// Calls per hour allowed by the user
            @available(*, deprecated, message: "Deprecated")
            static let rateLimit = HTTPHeader<Int>(field: "X-Rate-Limit")
            /// Date in UTC when toekn expires
            static let expiresAfter = HTTPHeader<Date>(field: "X-Expires-After")
        }
    }
}
