// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Store {
    var order: Order {
        Order(path: path + "/order")
    }

    struct Order {
        /// Path: `/store/order`
        let path: String

        /// Place an order for a pet
        func post(_ body: edgecases_change_access_control.Order) -> Request<edgecases_change_access_control.Order> {
            Request(method: "POST", url: path, body: body)
        }
    }
}
