// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

struct Animal: Codable {
    var className: String
    var color: String?

    init(className: String, color: String? = nil) {
        self.className = className
        self.color = color
    }
}
