// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

struct HasOnlyReadOnly: Codable {
    var bar: String?
    var foo: String?

    init(bar: String? = nil, foo: String? = nil) {
        self.bar = bar
        self.foo = foo
    }
}
