// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

struct MixedPropertiesAndAdditionalPropertiesClass: Codable {
    var uuid: UUID?
    var dateTime: Date?
    var map: [String: Animal]?

    init(uuid: UUID? = nil, dateTime: Date? = nil, map: [String: Animal]? = nil) {
        self.uuid = uuid
        self.dateTime = dateTime
        self.map = map
    }

    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.uuid = try values.decodeIfPresent(UUID.self, forKey: "uuid")
        self.dateTime = try values.decodeIfPresent(Date.self, forKey: "dateTime")
        self.map = try values.decodeIfPresent([String: Animal].self, forKey: "map")
    }

    func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(uuid, forKey: "uuid")
        try values.encodeIfPresent(dateTime, forKey: "dateTime")
        try values.encodeIfPresent(map, forKey: "map")
    }
}
