// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

struct NumberOnly: Codable {
    var justNumber: Double?

    init(justNumber: Double? = nil) {
        self.justNumber = justNumber
    }

    private enum CodingKeys: String, CodingKey {
        case justNumber = "JustNumber"
    }
}
