// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

enum OuterEnum: String, Codable, CaseIterable {
    case placed
    case approved
    case delivered
}
