// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Model for testing reserved words
struct Return: Codable {
    var `return`: Int?

    init(`return`: Int? = nil) {
        self.return = `return`
    }

    private enum CodingKeys: String, CodingKey {
        case `return`
    }
}
