// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct Store: Codable {
    public var pets: Pets

    public init(pets: Pets) {
        self.pets = pets
    }
}
