// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Pet.WithPetID {
    var uploadImage: UploadImage {
        UploadImage(path: path + "/uploadImage")
    }

    struct UploadImage {
        /// Path: `/pet/{petId}/uploadImage`
        let path: String

        /// Uploads an image
        func post(_ body: Data? = nil) -> Request<edgecases_change_access_control.APIResponse> {
            Request(path: path, method: "POST", body: body, id: "uploadFile")
        }
    }
}
