// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Three: Codable {
    public var kind: String
    public var foo: String

    public init(kind: String, foo: String) {
        self.kind = kind
        self.foo = foo
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.kind = try values.decode(String.self, forKey: "kind")
        self.foo = try values.decode(String.self, forKey: "foo")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(kind, forKey: "kind")
        try values.encode(foo, forKey: "foo")
    }
}
