// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct ContainerB: Codable {
    public var b: String?

    public init(b: String? = nil) {
        self.b = b
    }
}
