// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct ContainerC: Codable {
    public var c: String?

    public init(c: String? = nil) {
        self.c = c
    }
}
