// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct ContainerA: Codable {
    public var a: String?

    public init(a: String? = nil) {
        self.a = a
    }
}
