// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Model for testing model name same as property name
public struct Name: Codable {
    public var name: Int32
    public var snakeCase: Int32?
    public var property: String?
    public var _123Number: Int?

    public init(name: Int32, snakeCase: Int32? = nil, property: String? = nil, _123Number: Int? = nil) {
        self.name = name
        self.snakeCase = snakeCase
        self.property = property
        self._123Number = _123Number
    }

    private enum CodingKeys: String, CodingKey {
        case name
        case snakeCase = "snake_case"
        case property
        case _123Number = "123Number"
    }
}
