// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Item: Codable {
    public var weight: Int

    public init(weight: Int) {
        self.weight = weight
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.weight = try values.decode(Int.self, forKey: "weight")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(weight, forKey: "weight")
    }
}
