// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

public struct AdditionalPropertiesClass: Codable {
  public var mapProperty: [String: String]?
  public var mapOfMapProperty: [String: [String: String]]?

  public init(mapProperty: [String: String]? = nil, mapOfMapProperty: [String: [String: String]]? = nil) {
    self.mapProperty = mapProperty
    self.mapOfMapProperty = mapOfMapProperty
  }

  private enum CodingKeys: String, CodingKey {
    case mapProperty = "map_property"
    case mapOfMapProperty = "map_of_map_property"
  }
}
