// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct Image: Codable {
  public var id: String
  public var url: String

  public init(id: String, url: String) {
    self.id = id
    self.url = url
  }
}
