// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public enum OuterEnum: String, Codable, CaseIterable {
  case placed
  case approved
  case delivered
}
