// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo.Issues.Comments {
    public func commentID(_ commentID: Int) -> WithCommentID {
        WithCommentID(path: "\(path)/\(commentID)")
    }

    public struct WithCommentID {
        /// Path: `/repos/{owner}/{repo}/issues/comments/{comment_id}`
        public let path: String

        /// Get an issue comment
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/issues#get-an-issue-comment)
        public var get: Request<OctoKit.IssueComment> {
            Request(path: path, method: "GET", id: "issues/get-comment")
        }

        /// Update an issue comment
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/issues#update-an-issue-comment)
        public func patch(body: String) -> Request<OctoKit.IssueComment> {
            Request(path: path, method: "PATCH", body: ["body": body], id: "issues/update-comment")
        }

        /// Delete an issue comment
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/issues#delete-an-issue-comment)
        public var delete: Request<Void> {
            Request(path: path, method: "DELETE", id: "issues/delete-comment")
        }
    }
}
