// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Repos.WithOwner.WithRepo.Stats {
    public var contributors: Contributors {
        Contributors(path: path + "/contributors")
    }

    public struct Contributors {
        /// Path: `/repos/{owner}/{repo}/stats/contributors`
        public let path: String

        /// Get all contributor commit activity
        ///
        /// Returns the `total` number of commits authored by the contributor. In addition, the response includes a Weekly Hash (`weeks` array) with the following information:
        /// 
        /// *   `w` - Start of the week, given as a [Unix timestamp](http://en.wikipedia.org/wiki/Unix_time).
        /// *   `a` - Number of additions
        /// *   `d` - Number of deletions
        /// *   `c` - Number of commits
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/repos#get-all-contributor-commit-activity)
        public var get: Request<[OctoKit.ContributorActivity]> {
            Request(path: path, method: "GET", id: "repos/get-contributors-stats")
        }
    }
}
