// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import CoreData
import Get
import HTTPHeaders
import URLQueryEncoder

public enum Paths {}
