// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Error: Codable, Identifiable {
    public var id: Int
    public var message: String

    public init(id: Int, message: String) {
        self.id = id
        self.message = message
    }

    private enum CodingKeys: String, CodingKey {
        case id = "code"
        case message
    }
}
