// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Item: Codable {
    public var weight: Int

    public init(weight: Int) {
        self.weight = weight
    }
}
