// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Container: Codable {
    public var content: Content

    public enum Content: Codable {
        case containerA(ContainerA)
        case containerB(ContainerB)
        case containerC(ContainerC)

        public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            if let value = try? container.decode(ContainerA.self) {
                self = .containerA(value)
            } else if let value = try? container.decode(ContainerB.self) {
                self = .containerB(value)
            } else if let value = try? container.decode(ContainerC.self) {
                self = .containerC(value)
            } else {
                throw DecodingError.dataCorruptedError(in: container, debugDescription: "Failed to intialize `oneOf`")
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            switch self {
            case .containerA(let value): try container.encode(value)
            case .containerB(let value): try container.encode(value)
            case .containerC(let value): try container.encode(value)
            }
        }
    }

    public init(content: Content) {
        self.content = content
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.content = try values.decode(Content.self, forKey: "content")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(content, forKey: "content")
    }
}
