// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Collection: Codable {
    /// The unique collection identifier.
    public var id: Int
    /// The title of the collection.
    ///
    /// Example: "BBQ Classics"
    public var title: String
    /// A longer description of the collection.
    /// This is also a comment, but on a new line using the \n line break.
    ///
    /// Example: "The sun is shining? The BBQ is out? Check out this collection of recipes for the perfect summer BBQ."
    public var description: String
    /// The number of recipes in this collection.
    /// This is also a comment, but on a new line using the \r line break.
    ///
    /// Example: 27
    public var recipeCount: Int
    /// URLs to images for up to a maximum of four recipes in the collection.
    ///
    /// Example: ["https://img-global.cpcdn.com/recipes/65555efe64df98ce/m/photo.jpg"]
    public var previewImageURLs: [URL]

    public init(id: Int, title: String, description: String, recipeCount: Int, previewImageURLs: [URL]) {
        self.id = id
        self.title = title
        self.description = description
        self.recipeCount = recipeCount
        self.previewImageURLs = previewImageURLs
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case title
        case description
        case recipeCount = "recipe_count"
        case previewImageURLs = "preview_image_urls"
    }
}
