// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct User: Codable {
    /// The name of the user.
    ///
    /// Example: "Liam Nichols"
    public var name: String
    /// A URL to the user profile image, or null if one was not specified.
    ///
    /// Example: "https://img-global.cpcdn.com/users/f34ef79fabdb58a4/m/photo.jpg"
    public var imageURL: URL?

    public init(name: String, imageURL: URL? = nil) {
        self.name = name
        self.imageURL = imageURL
    }

    private enum CodingKeys: String, CodingKey {
        case name
        case imageURL = "image_url"
    }
}
