// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths.Collections {
    public func id(_ id: Int) -> WithID {
        WithID(path: "\(path)/\(id)")
    }

    public struct WithID {
        /// Path: `/api/collections/{id}`
        public let path: String

        /// Find a Collection by ID
        ///
        /// Returns a single Collection model associated with the given identifier.
        public var get: Request<cookpad.Collection> {
            Request(path: path, method: "GET", id: "getCollection")
        }
    }
}
