// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths.Enterprises.WithEnterprise.Actions.RunnerGroups.WithRunnerGroupID {
    public var organizations: Organizations {
        Organizations(path: path + "/organizations")
    }

    public struct Organizations {
        /// Path: `/enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/organizations`
        public let path: String

        /// List organization access to a self-hosted runner group in an enterprise
        ///
        /// Lists the organizations with access to a self-hosted runner group.
        /// 
        /// You must authenticate using an access token with the `manage_runners:enterprise` scope to use this endpoint.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/enterprise-admin#list-organization-access-to-a-self-hosted-runner-group-in-a-enterprise)
        public func get(perPage: Int? = nil, page: Int? = nil) -> Request<GetResponse> {
            Request(method: "GET", url: path, query: makeGetQuery(perPage, page))
        }

        public struct GetResponse: Decodable {
            public var totalCount: Double
            public var organizations: [OctoKit.OrganizationSimple]

            public init(totalCount: Double, organizations: [OctoKit.OrganizationSimple]) {
                self.totalCount = totalCount
                self.organizations = organizations
            }

            private enum CodingKeys: String, CodingKey {
                case totalCount = "total_count"
                case organizations
            }
        }

        private func makeGetQuery(_ perPage: Int?, _ page: Int?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(perPage, forKey: "per_page")
            encoder.encode(page, forKey: "page")
            return encoder.items
        }

        /// Set organization access for a self-hosted runner group in an enterprise
        ///
        /// Replaces the list of organizations that have access to a self-hosted runner configured in an enterprise.
        /// 
        /// You must authenticate using an access token with the `manage_runners:enterprise` scope to use this endpoint.
        ///
        /// [API method documentation](https://docs.github.com/rest/reference/enterprise-admin#set-organization-access-to-a-self-hosted-runner-group-in-an-enterprise)
        public func put(selectedOrganizationIDs: [Int]) -> Request<Void> {
            Request(method: "PUT", url: path, body: ["selected_organization_ids": selectedOrganizationIDs])
        }
    }
}
