// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

public struct ActionsRepositoryPermissions: Codable {
    /// Whether GitHub Actions is enabled on the repository.
    public var isEnabled: Bool
    /// The permissions policy that controls the actions that are allowed to run. Can be one of: `all`, `local_only`, or `selected`.
    public var allowedActions: AllowedActions?
    /// The API URL to use to get or set the actions that are allowed to run, when `allowed_actions` is set to `selected`.
    public var selectedActionsURL: String?

    public init(isEnabled: Bool, allowedActions: AllowedActions? = nil, selectedActionsURL: String? = nil) {
        self.isEnabled = isEnabled
        self.allowedActions = allowedActions
        self.selectedActionsURL = selectedActionsURL
    }

    private enum CodingKeys: String, CodingKey {
        case isEnabled = "enabled"
        case allowedActions = "allowed_actions"
        case selectedActionsURL = "selected_actions_url"
    }
}
