// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

public struct AdvancedSecurityActiveCommitters: Codable {
    /// Example: 25
    public var totalAdvancedSecurityCommitters: Int?
    public var repositories: [AdvancedSecurityActiveCommittersRepository]

    public init(totalAdvancedSecurityCommitters: Int? = nil, repositories: [AdvancedSecurityActiveCommittersRepository]) {
        self.totalAdvancedSecurityCommitters = totalAdvancedSecurityCommitters
        self.repositories = repositories
    }

    private enum CodingKeys: String, CodingKey {
        case totalAdvancedSecurityCommitters = "total_advanced_security_committers"
        case repositories
    }
}
