// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

public struct CheckAnnotation: Codable {
    /// Example: "README.md"
    public var path: String
    public var startLine: Int
    public var endLine: Int
    public var startColumn: Int?
    /// Example: 10
    public var endColumn: Int?
    /// Example: "warning"
    public var annotationLevel: String?
    /// Example: "Spell Checker"
    public var title: String?
    /// Example: "Check your spelling for 'banaas'."
    public var message: String?
    /// Example: "Do you mean 'bananas' or 'banana'?"
    public var rawDetails: String?
    public var blobHref: String

    public init(path: String, startLine: Int, endLine: Int, startColumn: Int? = nil, endColumn: Int? = nil, annotationLevel: String? = nil, title: String? = nil, message: String? = nil, rawDetails: String? = nil, blobHref: String) {
        self.path = path
        self.startLine = startLine
        self.endLine = endLine
        self.startColumn = startColumn
        self.endColumn = endColumn
        self.annotationLevel = annotationLevel
        self.title = title
        self.message = message
        self.rawDetails = rawDetails
        self.blobHref = blobHref
    }

    private enum CodingKeys: String, CodingKey {
        case path
        case startLine = "start_line"
        case endLine = "end_line"
        case startColumn = "start_column"
        case endColumn = "end_column"
        case annotationLevel = "annotation_level"
        case title
        case message
        case rawDetails = "raw_details"
        case blobHref = "blob_href"
    }
}
