// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct CloneTraffic: Codable {
    /// Example: 173
    public var count: Int
    /// Example: 128
    public var uniques: Int
    public var clones: [Traffic]

    public init(count: Int, uniques: Int, clones: [Traffic]) {
        self.count = count
        self.uniques = uniques
        self.clones = clones
    }
}
