// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

/// Code of Conduct Simple
public struct CodeOfConductSimple: Codable {
    /// Example: "https://api.github.com/repos/github/docs/community/code_of_conduct"
    public var url: URL
    /// Example: "citizen_code_of_conduct"
    public var key: String
    /// Example: "Citizen Code of Conduct"
    public var name: String
    /// Example: "https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md"
    public var htmlURL: URL?

    public init(url: URL, key: String, name: String, htmlURL: URL? = nil) {
        self.url = url
        self.key = key
        self.name = name
        self.htmlURL = htmlURL
    }

    private enum CodingKeys: String, CodingKey {
        case url
        case key
        case name
        case htmlURL = "html_url"
    }
}
