// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

public struct CodeScanningAlertRuleSummary: Codable {
    /// A unique identifier for the rule used to detect the alert.
    public var id: String?
    /// The name of the rule used to detect the alert.
    public var name: String?
    /// The severity of the alert.
    public var severity: Severity?
    /// A short description of the rule used to detect the alert.
    public var description: String?

    /// The severity of the alert.
    public enum Severity: String, Codable, CaseIterable {
        case `none`
        case note
        case warning
        case error
    }

    public init(id: String? = nil, name: String? = nil, severity: Severity? = nil, description: String? = nil) {
        self.id = id
        self.name = name
        self.severity = severity
        self.description = description
    }
}
