// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct Email: Codable {
    /// Example: "octocat@github.com"
    public var email: String
    /// Example: true
    public var isPrimary: Bool
    /// Example: true
    public var isVerified: Bool
    /// Example: "public"
    public var visibility: String?

    public init(email: String, isPrimary: Bool, isVerified: Bool, visibility: String? = nil) {
        self.email = email
        self.isPrimary = isPrimary
        self.isVerified = isVerified
        self.visibility = visibility
    }

    private enum CodingKeys: String, CodingKey {
        case email
        case isPrimary = "primary"
        case isVerified = "verified"
        case visibility
    }
}
