// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct GistCommit: Codable {
    /// Example: "https://api.github.com/gists/aa5a315d61ae9438b18d/57a7f021a713b1c5a6a199b54cc514735d2d462f"
    public var url: URL
    /// Example: "57a7f021a713b1c5a6a199b54cc514735d2d462f"
    public var version: String
    /// Simple User
    public var user: SimpleUser?
    public var changeStatus: ChangeStatus
    /// Example: "2010-04-14T02:15:15Z"
    public var committedAt: Date

    public struct ChangeStatus: Codable {
        public var total: Int?
        public var additions: Int?
        public var deletions: Int?

        public init(total: Int? = nil, additions: Int? = nil, deletions: Int? = nil) {
            self.total = total
            self.additions = additions
            self.deletions = deletions
        }
    }

    public init(url: URL, version: String, user: SimpleUser? = nil, changeStatus: ChangeStatus, committedAt: Date) {
        self.url = url
        self.version = version
        self.user = user
        self.changeStatus = changeStatus
        self.committedAt = committedAt
    }

    private enum CodingKeys: String, CodingKey {
        case url
        case version
        case user
        case changeStatus = "change_status"
        case committedAt = "committed_at"
    }
}
