// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct GitignoreTemplate: Codable {
    /// Example: "C"
    public var name: String
    /// Example:
    ///
    /// "# Object files
    /// *.o
    /// 
    /// # Libraries
    /// *.lib
    /// *.a
    /// 
    /// # Shared objects (inc. Windows DLLs)
    /// *.dll
    /// *.so
    /// *.so.*
    /// *.dylib
    /// 
    /// # Executables
    /// *.exe
    /// *.out
    /// *.app
    /// "
    public var source: String

    public init(name: String, source: String) {
        self.name = name
        self.source = source
    }
}
