// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Webhook
///
/// Webhooks for repositories.
public struct Hook: Codable {
    public var type: String
    /// Unique identifier of the webhook.
    ///
    /// Example: 42
    public var id: Int
    /// The name of a valid service, use 'web' for a webhook.
    ///
    /// Example: "web"
    public var name: String
    /// Determines whether the hook is actually triggered on pushes.
    ///
    /// Example: true
    public var isActive: Bool
    /// Determines what events the hook is triggered for. Default: ['push'].
    ///
    /// Example: ["push", "pull_request"]
    public var events: [String]
    public var config: Config
    /// Example: "2011-09-06T20:39:23Z"
    public var updatedAt: Date
    /// Example: "2011-09-06T17:26:27Z"
    public var createdAt: Date
    /// Example: "https://api.github.com/repos/octocat/Hello-World/hooks/1"
    public var url: URL
    /// Example: "https://api.github.com/repos/octocat/Hello-World/hooks/1/test"
    public var testURL: URL
    /// Example: "https://api.github.com/repos/octocat/Hello-World/hooks/1/pings"
    public var pingURL: URL
    /// Example: "https://api.github.com/repos/octocat/Hello-World/hooks/1/deliveries"
    public var deliveriesURL: URL?
    /// Hook Response
    public var lastResponse: HookResponse

    public struct Config: Codable {
        /// Example: "foo@bar.com"
        public var email: String?
        /// Example: "foo"
        public var password: String?
        /// Example: "roomer"
        public var room: String?
        /// Example: "foo"
        public var subdomain: String?
        /// The URL to which the payloads will be delivered.
        ///
        /// Example: "https://example.com/webhook"
        public var url: URL?
        public var insecureSSL: WebhookConfigInsecureSSL?
        /// The media type used to serialize the payloads. Supported values include `json` and `form`. The default is `form`.
        ///
        /// Example: "json"
        public var contentType: String?
        /// Example: "sha256"
        public var digest: String?
        /// If provided, the `secret` will be used as the `key` to generate the HMAC hex digest value for [delivery signature headers](https://docs.github.com/webhooks/event-payloads/#delivery-headers).
        ///
        /// Example: "********"
        public var secret: String?
        /// Example: "abc"
        public var token: String?

        public init(email: String? = nil, password: String? = nil, room: String? = nil, subdomain: String? = nil, url: URL? = nil, insecureSSL: WebhookConfigInsecureSSL? = nil, contentType: String? = nil, digest: String? = nil, secret: String? = nil, token: String? = nil) {
            self.email = email
            self.password = password
            self.room = room
            self.subdomain = subdomain
            self.url = url
            self.insecureSSL = insecureSSL
            self.contentType = contentType
            self.digest = digest
            self.secret = secret
            self.token = token
        }

        private enum CodingKeys: String, CodingKey {
            case email
            case password
            case room
            case subdomain
            case url
            case insecureSSL = "insecure_ssl"
            case contentType = "content_type"
            case digest
            case secret
            case token
        }
    }

    public init(type: String, id: Int, name: String, isActive: Bool, events: [String], config: Config, updatedAt: Date, createdAt: Date, url: URL, testURL: URL, pingURL: URL, deliveriesURL: URL? = nil, lastResponse: HookResponse) {
        self.type = type
        self.id = id
        self.name = name
        self.isActive = isActive
        self.events = events
        self.config = config
        self.updatedAt = updatedAt
        self.createdAt = createdAt
        self.url = url
        self.testURL = testURL
        self.pingURL = pingURL
        self.deliveriesURL = deliveriesURL
        self.lastResponse = lastResponse
    }

    private enum CodingKeys: String, CodingKey {
        case type
        case id
        case name
        case isActive = "active"
        case events
        case config
        case updatedAt = "updated_at"
        case createdAt = "created_at"
        case url
        case testURL = "test_url"
        case pingURL = "ping_url"
        case deliveriesURL = "deliveries_url"
        case lastResponse = "last_response"
    }
}
