// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct HookResponse: Codable {
    public var code: Int?
    public var status: String?
    public var message: String?

    public init(code: Int? = nil, status: String? = nil, message: String? = nil) {
        self.code = code
        self.status = status
        self.message = message
    }
}
