// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

public struct Hovercard: Codable {
    public var contexts: [Context]

    public struct Context: Codable {
        public var message: String
        public var octicon: String

        public init(message: String, octicon: String) {
            self.message = message
            self.octicon = octicon
        }
    }

    public init(contexts: [Context]) {
        self.contexts = contexts
    }
}
