// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

/// Interaction Limits
///
/// Interaction limit settings.
public struct InteractionLimitResponse: Codable {
    /// The type of GitHub user that can comment, open issues, or create pull requests while the interaction limit is in effect. Can be one of: `existing_users`, `contributors_only`, `collaborators_only`.
    ///
    /// Example: "collaborators_only"
    public var limit: InteractionGroup
    /// Example: "repository"
    public var origin: String
    /// Example: "2018-08-17T04:18:39Z"
    public var expiresAt: Date

    public init(limit: InteractionGroup, origin: String, expiresAt: Date) {
        self.limit = limit
        self.origin = origin
        self.expiresAt = expiresAt
    }

    private enum CodingKeys: String, CodingKey {
        case limit
        case origin
        case expiresAt = "expires_at"
    }
}
