// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

/// The type of GitHub user that can comment, open issues, or create pull requests while the interaction limit is in effect. Can be one of: `existing_users`, `contributors_only`, `collaborators_only`.
///
/// Example: "collaborators_only"
public enum InteractionGroup: String, Codable, CaseIterable {
    case existingUsers = "existing_users"
    case contributorsOnly = "contributors_only"
    case collaboratorsOnly = "collaborators_only"
}
