// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Information of a job execution in a workflow run
public struct Job: Codable {
    /// The id of the job.
    ///
    /// Example: 21
    public var id: Int
    /// The id of the associated workflow run.
    public var runID: Int
    /// Example: "https://api.github.com/repos/github/hello-world/actions/runs/5"
    public var runURL: String
    /// Attempt number of the associated workflow run, 1 for first attempt and higher if the workflow was re-run.
    public var runAttempt: Int?
    /// Example: "MDg6Q2hlY2tSdW40"
    public var nodeID: String
    /// The SHA of the commit that is being run.
    ///
    /// Example: "009b8a3a9ccbb128af87f9b1c0f4c62e8a304f6d"
    public var headSha: String
    /// Example: "https://api.github.com/repos/github/hello-world/actions/jobs/21"
    public var url: String
    /// Example: "https://github.com/github/hello-world/runs/4"
    public var htmlURL: String?
    /// The phase of the lifecycle that the job is currently in.
    ///
    /// Example: "queued"
    public var status: Status
    /// The outcome of the job.
    ///
    /// Example: "success"
    public var conclusion: String?
    /// The time that the job started, in ISO 8601 format.
    ///
    /// Example: "2019-08-08T08:00:00-07:00"
    public var startedAt: Date
    /// The time that the job finished, in ISO 8601 format.
    ///
    /// Example: "2019-08-08T08:00:00-07:00"
    public var completedAt: Date?
    /// The name of the job.
    ///
    /// Example: "test-coverage"
    public var name: String
    /// Steps in this job.
    public var steps: [Step]?
    /// Example: "https://api.github.com/repos/github/hello-world/check-runs/4"
    public var checkRunURL: String
    /// Labels for the workflow job. Specified by the "runs_on" attribute in the action's workflow file.
    ///
    /// Example: ["self-hosted", "foo", "bar"]
    public var labels: [String]
    /// The ID of the runner to which this job has been assigned. (If a runner hasn't yet been assigned, this will be null.)
    public var runnerID: Int?
    /// The name of the runner to which this job has been assigned. (If a runner hasn't yet been assigned, this will be null.)
    ///
    /// Example: "my runner"
    public var runnerName: String?
    /// The ID of the runner group to which this job has been assigned. (If a runner hasn't yet been assigned, this will be null.)
    public var runnerGroupID: Int?
    /// The name of the runner group to which this job has been assigned. (If a runner hasn't yet been assigned, this will be null.)
    ///
    /// Example: "my runner group"
    public var runnerGroupName: String?

    /// The phase of the lifecycle that the job is currently in.
    ///
    /// Example: "queued"
    public enum Status: String, Codable, CaseIterable {
        case queued
        case inProgress = "in_progress"
        case completed
    }

    public struct Step: Codable {
        /// The phase of the lifecycle that the job is currently in.
        ///
        /// Example: "queued"
        public var status: Status
        /// The outcome of the job.
        ///
        /// Example: "success"
        public var conclusion: String?
        /// The name of the job.
        ///
        /// Example: "test-coverage"
        public var name: String
        public var number: Int
        /// The time that the step started, in ISO 8601 format.
        ///
        /// Example: "2019-08-08T08:00:00-07:00"
        public var startedAt: Date?
        /// The time that the job finished, in ISO 8601 format.
        ///
        /// Example: "2019-08-08T08:00:00-07:00"
        public var completedAt: Date?

        /// The phase of the lifecycle that the job is currently in.
        ///
        /// Example: "queued"
        public enum Status: String, Codable, CaseIterable {
            case queued
            case inProgress = "in_progress"
            case completed
        }

        public init(status: Status, conclusion: String? = nil, name: String, number: Int, startedAt: Date? = nil, completedAt: Date? = nil) {
            self.status = status
            self.conclusion = conclusion
            self.name = name
            self.number = number
            self.startedAt = startedAt
            self.completedAt = completedAt
        }

        private enum CodingKeys: String, CodingKey {
            case status
            case conclusion
            case name
            case number
            case startedAt = "started_at"
            case completedAt = "completed_at"
        }
    }

    public init(id: Int, runID: Int, runURL: String, runAttempt: Int? = nil, nodeID: String, headSha: String, url: String, htmlURL: String? = nil, status: Status, conclusion: String? = nil, startedAt: Date, completedAt: Date? = nil, name: String, steps: [Step]? = nil, checkRunURL: String, labels: [String], runnerID: Int? = nil, runnerName: String? = nil, runnerGroupID: Int? = nil, runnerGroupName: String? = nil) {
        self.id = id
        self.runID = runID
        self.runURL = runURL
        self.runAttempt = runAttempt
        self.nodeID = nodeID
        self.headSha = headSha
        self.url = url
        self.htmlURL = htmlURL
        self.status = status
        self.conclusion = conclusion
        self.startedAt = startedAt
        self.completedAt = completedAt
        self.name = name
        self.steps = steps
        self.checkRunURL = checkRunURL
        self.labels = labels
        self.runnerID = runnerID
        self.runnerName = runnerName
        self.runnerGroupID = runnerGroupID
        self.runnerGroupName = runnerGroupName
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case runID = "run_id"
        case runURL = "run_url"
        case runAttempt = "run_attempt"
        case nodeID = "node_id"
        case headSha = "head_sha"
        case url
        case htmlURL = "html_url"
        case status
        case conclusion
        case startedAt = "started_at"
        case completedAt = "completed_at"
        case name
        case steps
        case checkRunURL = "check_run_url"
        case labels
        case runnerID = "runner_id"
        case runnerName = "runner_name"
        case runnerGroupID = "runner_group_id"
        case runnerGroupName = "runner_group_name"
    }
}
