// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

public struct LabelSearchResultItem: Codable {
    public var id: Int
    public var nodeID: String
    public var url: URL
    public var name: String
    public var color: String
    public var isDefault: Bool
    public var description: String?
    public var score: Double
    /// Search Result Text Matches
    public var textMatches: [SearchResultTextMatch]?

    public init(id: Int, nodeID: String, url: URL, name: String, color: String, isDefault: Bool, description: String? = nil, score: Double, textMatches: [SearchResultTextMatch]? = nil) {
        self.id = id
        self.nodeID = nodeID
        self.url = url
        self.name = name
        self.color = color
        self.isDefault = isDefault
        self.description = description
        self.score = score
        self.textMatches = textMatches
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case nodeID = "node_id"
        case url
        case name
        case color
        case isDefault = "default"
        case description
        case score
        case textMatches = "text_matches"
    }
}
