// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// A collection of related issues and pull requests.
public struct Milestone: Codable {
    /// Example: "https://api.github.com/repos/octocat/Hello-World/milestones/1"
    public var url: URL
    /// Example: "https://github.com/octocat/Hello-World/milestones/v1.0"
    public var htmlURL: URL
    /// Example: "https://api.github.com/repos/octocat/Hello-World/milestones/1/labels"
    public var labelsURL: URL
    /// Example: 1002604
    public var id: Int
    /// Example: "MDk6TWlsZXN0b25lMTAwMjYwNA=="
    public var nodeID: String
    /// The number of the milestone.
    ///
    /// Example: 42
    public var number: Int
    /// The state of the milestone.
    ///
    /// Example: "open"
    public var state: State
    /// The title of the milestone.
    ///
    /// Example: "v1.0"
    public var title: String
    /// Example: "Tracking milestone for version 1.0"
    public var description: String?
    /// Simple User
    public var creator: SimpleUser?
    public var openIssues: Int
    public var closedIssues: Int
    /// Example: "2011-04-10T20:09:31Z"
    public var createdAt: Date
    /// Example: "2014-03-03T18:58:10Z"
    public var updatedAt: Date
    /// Example: "2013-02-12T13:22:01Z"
    public var closedAt: Date?
    /// Example: "2012-10-09T23:39:01Z"
    public var dueOn: Date?

    /// The state of the milestone.
    ///
    /// Example: "open"
    public enum State: String, Codable, CaseIterable {
        case `open`
        case closed
    }

    public init(url: URL, htmlURL: URL, labelsURL: URL, id: Int, nodeID: String, number: Int, state: State, title: String, description: String? = nil, creator: SimpleUser? = nil, openIssues: Int, closedIssues: Int, createdAt: Date, updatedAt: Date, closedAt: Date? = nil, dueOn: Date? = nil) {
        self.url = url
        self.htmlURL = htmlURL
        self.labelsURL = labelsURL
        self.id = id
        self.nodeID = nodeID
        self.number = number
        self.state = state
        self.title = title
        self.description = description
        self.creator = creator
        self.openIssues = openIssues
        self.closedIssues = closedIssues
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.closedAt = closedAt
        self.dueOn = dueOn
    }

    private enum CodingKeys: String, CodingKey {
        case url
        case htmlURL = "html_url"
        case labelsURL = "labels_url"
        case id
        case nodeID = "node_id"
        case number
        case state
        case title
        case description
        case creator
        case openIssues = "open_issues"
        case closedIssues = "closed_issues"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case closedAt = "closed_at"
        case dueOn = "due_on"
    }
}
