// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

public struct PagesSourceHash: Codable {
    public var branch: String
    public var path: String

    public init(branch: String, path: String) {
        self.branch = branch
        self.path = path
    }
}
