// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct PrivateUser: Codable {
    /// Example: "octocat"
    public var login: String
    public var id: Int
    /// Example: "MDQ6VXNlcjE="
    public var nodeID: String
    /// Example: "https://github.com/images/error/octocat_happy.gif"
    public var avatarURL: URL
    /// Example: "41d064eb2195891e12d0413f63227ea7"
    public var gravatarID: String?
    /// Example: "https://api.github.com/users/octocat"
    public var url: URL
    /// Example: "https://github.com/octocat"
    public var htmlURL: URL
    /// Example: "https://api.github.com/users/octocat/followers"
    public var followersURL: URL
    /// Example: "https://api.github.com/users/octocat/following{/other_user}"
    public var followingURL: String
    /// Example: "https://api.github.com/users/octocat/gists{/gist_id}"
    public var gistsURL: String
    /// Example: "https://api.github.com/users/octocat/starred{/owner}{/repo}"
    public var starredURL: String
    /// Example: "https://api.github.com/users/octocat/subscriptions"
    public var subscriptionsURL: URL
    /// Example: "https://api.github.com/users/octocat/orgs"
    public var organizationsURL: URL
    /// Example: "https://api.github.com/users/octocat/repos"
    public var reposURL: URL
    /// Example: "https://api.github.com/users/octocat/events{/privacy}"
    public var eventsURL: String
    /// Example: "https://api.github.com/users/octocat/received_events"
    public var receivedEventsURL: URL
    /// Example: "User"
    public var type: String
    public var isSiteAdmin: Bool
    /// Example: "monalisa octocat"
    public var name: String?
    /// Example: "GitHub"
    public var company: String?
    /// Example: "https://github.com/blog"
    public var blog: String?
    /// Example: "San Francisco"
    public var location: String?
    /// Example: "octocat@github.com"
    public var email: String?
    public var isHireable: Bool?
    /// Example: "There once was..."
    public var bio: String?
    /// Example: "monalisa"
    public var twitterUsername: String?
    public var publicRepos: Int
    public var publicGists: Int
    /// Example: 20
    public var followers: Int
    public var following: Int
    /// Example: "2008-01-14T04:33:35Z"
    public var createdAt: Date
    /// Example: "2008-01-14T04:33:35Z"
    public var updatedAt: Date
    /// Example: 81
    public var privateGists: Int
    /// Example: 100
    public var totalPrivateRepos: Int
    /// Example: 100
    public var ownedPrivateRepos: Int
    /// Example: 10000
    public var diskUsage: Int
    public var collaborators: Int
    /// Example: true
    public var isTwoFactorAuthentication: Bool
    public var plan: Plan?
    public var suspendedAt: Date?
    public var isBusinessPlus: Bool?
    public var ldapDn: String?

    public struct Plan: Codable {
        public var collaborators: Int
        public var name: String
        public var space: Int
        public var privateRepos: Int

        public init(collaborators: Int, name: String, space: Int, privateRepos: Int) {
            self.collaborators = collaborators
            self.name = name
            self.space = space
            self.privateRepos = privateRepos
        }

        private enum CodingKeys: String, CodingKey {
            case collaborators
            case name
            case space
            case privateRepos = "private_repos"
        }
    }

    public init(login: String, id: Int, nodeID: String, avatarURL: URL, gravatarID: String? = nil, url: URL, htmlURL: URL, followersURL: URL, followingURL: String, gistsURL: String, starredURL: String, subscriptionsURL: URL, organizationsURL: URL, reposURL: URL, eventsURL: String, receivedEventsURL: URL, type: String, isSiteAdmin: Bool, name: String? = nil, company: String? = nil, blog: String? = nil, location: String? = nil, email: String? = nil, isHireable: Bool? = nil, bio: String? = nil, twitterUsername: String? = nil, publicRepos: Int, publicGists: Int, followers: Int, following: Int, createdAt: Date, updatedAt: Date, privateGists: Int, totalPrivateRepos: Int, ownedPrivateRepos: Int, diskUsage: Int, collaborators: Int, isTwoFactorAuthentication: Bool, plan: Plan? = nil, suspendedAt: Date? = nil, isBusinessPlus: Bool? = nil, ldapDn: String? = nil) {
        self.login = login
        self.id = id
        self.nodeID = nodeID
        self.avatarURL = avatarURL
        self.gravatarID = gravatarID
        self.url = url
        self.htmlURL = htmlURL
        self.followersURL = followersURL
        self.followingURL = followingURL
        self.gistsURL = gistsURL
        self.starredURL = starredURL
        self.subscriptionsURL = subscriptionsURL
        self.organizationsURL = organizationsURL
        self.reposURL = reposURL
        self.eventsURL = eventsURL
        self.receivedEventsURL = receivedEventsURL
        self.type = type
        self.isSiteAdmin = isSiteAdmin
        self.name = name
        self.company = company
        self.blog = blog
        self.location = location
        self.email = email
        self.isHireable = isHireable
        self.bio = bio
        self.twitterUsername = twitterUsername
        self.publicRepos = publicRepos
        self.publicGists = publicGists
        self.followers = followers
        self.following = following
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.privateGists = privateGists
        self.totalPrivateRepos = totalPrivateRepos
        self.ownedPrivateRepos = ownedPrivateRepos
        self.diskUsage = diskUsage
        self.collaborators = collaborators
        self.isTwoFactorAuthentication = isTwoFactorAuthentication
        self.plan = plan
        self.suspendedAt = suspendedAt
        self.isBusinessPlus = isBusinessPlus
        self.ldapDn = ldapDn
    }

    private enum CodingKeys: String, CodingKey {
        case login
        case id
        case nodeID = "node_id"
        case avatarURL = "avatar_url"
        case gravatarID = "gravatar_id"
        case url
        case htmlURL = "html_url"
        case followersURL = "followers_url"
        case followingURL = "following_url"
        case gistsURL = "gists_url"
        case starredURL = "starred_url"
        case subscriptionsURL = "subscriptions_url"
        case organizationsURL = "organizations_url"
        case reposURL = "repos_url"
        case eventsURL = "events_url"
        case receivedEventsURL = "received_events_url"
        case type
        case isSiteAdmin = "site_admin"
        case name
        case company
        case blog
        case location
        case email
        case isHireable = "hireable"
        case bio
        case twitterUsername = "twitter_username"
        case publicRepos = "public_repos"
        case publicGists = "public_gists"
        case followers
        case following
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case privateGists = "private_gists"
        case totalPrivateRepos = "total_private_repos"
        case ownedPrivateRepos = "owned_private_repos"
        case diskUsage = "disk_usage"
        case collaborators
        case isTwoFactorAuthentication = "two_factor_authentication"
        case plan
        case suspendedAt = "suspended_at"
        case isBusinessPlus = "business_plus"
        case ldapDn = "ldap_dn"
    }
}
