// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Projects are a way to organize columns and cards of work.
public struct Project: Codable {
    /// Example: "https://api.github.com/repos/api-playground/projects-test"
    public var ownerURL: URL
    /// Example: "https://api.github.com/projects/1002604"
    public var url: URL
    /// Example: "https://github.com/api-playground/projects-test/projects/12"
    public var htmlURL: URL
    /// Example: "https://api.github.com/projects/1002604/columns"
    public var columnsURL: URL
    /// Example: 1002604
    public var id: Int
    /// Example: "MDc6UHJvamVjdDEwMDI2MDQ="
    public var nodeID: String
    /// Name of the project
    ///
    /// Example: "Week One Sprint"
    public var name: String
    /// Body of the project
    ///
    /// Example: "This project represents the sprint of the first week in January"
    public var body: String?
    public var number: Int
    /// State of the project; either 'open' or 'closed'
    ///
    /// Example: "open"
    public var state: String
    /// Simple User
    public var creator: SimpleUser?
    /// Example: "2011-04-10T20:09:31Z"
    public var createdAt: Date
    /// Example: "2014-03-03T18:58:10Z"
    public var updatedAt: Date
    /// The baseline permission that all organization members have on this project. Only present if owner is an organization.
    public var organizationPermission: OrganizationPermission?
    /// Whether or not this project can be seen by everyone. Only present if owner is an organization.
    public var isPrivate: Bool?

    /// The baseline permission that all organization members have on this project. Only present if owner is an organization.
    public enum OrganizationPermission: String, Codable, CaseIterable {
        case read
        case write
        case admin
        case `none`
    }

    public init(ownerURL: URL, url: URL, htmlURL: URL, columnsURL: URL, id: Int, nodeID: String, name: String, body: String? = nil, number: Int, state: String, creator: SimpleUser? = nil, createdAt: Date, updatedAt: Date, organizationPermission: OrganizationPermission? = nil, isPrivate: Bool? = nil) {
        self.ownerURL = ownerURL
        self.url = url
        self.htmlURL = htmlURL
        self.columnsURL = columnsURL
        self.id = id
        self.nodeID = nodeID
        self.name = name
        self.body = body
        self.number = number
        self.state = state
        self.creator = creator
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.organizationPermission = organizationPermission
        self.isPrivate = isPrivate
    }

    private enum CodingKeys: String, CodingKey {
        case ownerURL = "owner_url"
        case url
        case htmlURL = "html_url"
        case columnsURL = "columns_url"
        case id
        case nodeID = "node_id"
        case name
        case body
        case number
        case state
        case creator
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case organizationPermission = "organization_permission"
        case isPrivate = "private"
    }
}
