// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Project cards represent a scope of work.
public struct ProjectCard: Codable {
    /// Example: "https://api.github.com/projects/columns/cards/1478"
    public var url: URL
    /// The project card's ID
    ///
    /// Example: 42
    public var id: Int
    /// Example: "MDExOlByb2plY3RDYXJkMTQ3OA=="
    public var nodeID: String
    /// Example: "Add payload for delete Project column"
    public var note: String?
    /// Simple User
    public var creator: SimpleUser?
    /// Example: "2016-09-05T14:21:06Z"
    public var createdAt: Date
    /// Example: "2016-09-05T14:20:22Z"
    public var updatedAt: Date
    /// Whether or not the card is archived
    ///
    /// Example: false
    public var isArchived: Bool?
    public var columnName: String?
    public var projectID: String?
    /// Example: "https://api.github.com/projects/columns/367"
    public var columnURL: URL
    /// Example: "https://api.github.com/repos/api-playground/projects-test/issues/3"
    public var contentURL: URL?
    /// Example: "https://api.github.com/projects/120"
    public var projectURL: URL

    public init(url: URL, id: Int, nodeID: String, note: String? = nil, creator: SimpleUser? = nil, createdAt: Date, updatedAt: Date, isArchived: Bool? = nil, columnName: String? = nil, projectID: String? = nil, columnURL: URL, contentURL: URL? = nil, projectURL: URL) {
        self.url = url
        self.id = id
        self.nodeID = nodeID
        self.note = note
        self.creator = creator
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.isArchived = isArchived
        self.columnName = columnName
        self.projectID = projectID
        self.columnURL = columnURL
        self.contentURL = contentURL
        self.projectURL = projectURL
    }

    private enum CodingKeys: String, CodingKey {
        case url
        case id
        case nodeID = "node_id"
        case note
        case creator
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case isArchived = "archived"
        case columnName = "column_name"
        case projectID = "project_id"
        case columnURL = "column_url"
        case contentURL = "content_url"
        case projectURL = "project_url"
    }
}
