// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Project columns contain cards of work.
public struct ProjectColumn: Codable {
    /// Example: "https://api.github.com/projects/columns/367"
    public var url: URL
    /// Example: "https://api.github.com/projects/120"
    public var projectURL: URL
    /// Example: "https://api.github.com/projects/columns/367/cards"
    public var cardsURL: URL
    /// The unique identifier of the project column
    ///
    /// Example: 42
    public var id: Int
    /// Example: "MDEzOlByb2plY3RDb2x1bW4zNjc="
    public var nodeID: String
    /// Name of the project column
    ///
    /// Example: "Remaining tasks"
    public var name: String
    /// Example: "2016-09-05T14:18:44Z"
    public var createdAt: Date
    /// Example: "2016-09-05T14:22:28Z"
    public var updatedAt: Date

    public init(url: URL, projectURL: URL, cardsURL: URL, id: Int, nodeID: String, name: String, createdAt: Date, updatedAt: Date) {
        self.url = url
        self.projectURL = projectURL
        self.cardsURL = cardsURL
        self.id = id
        self.nodeID = nodeID
        self.name = name
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    private enum CodingKeys: String, CodingKey {
        case url
        case projectURL = "project_url"
        case cardsURL = "cards_url"
        case id
        case nodeID = "node_id"
        case name
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}
