// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

public struct PullRequestMinimal: Codable {
    public var id: Int
    public var number: Int
    public var url: String
    public var head: Head
    public var base: Base

    public struct Head: Codable {
        public var ref: String
        public var sha: String
        public var repo: Repo

        public struct Repo: Codable {
            public var id: Int
            public var url: String
            public var name: String

            public init(id: Int, url: String, name: String) {
                self.id = id
                self.url = url
                self.name = name
            }
        }

        public init(ref: String, sha: String, repo: Repo) {
            self.ref = ref
            self.sha = sha
            self.repo = repo
        }
    }

    public struct Base: Codable {
        public var ref: String
        public var sha: String
        public var repo: Repo

        public struct Repo: Codable {
            public var id: Int
            public var url: String
            public var name: String

            public init(id: Int, url: String, name: String) {
                self.id = id
                self.url = url
                self.name = name
            }
        }

        public init(ref: String, sha: String, repo: Repo) {
            self.ref = ref
            self.sha = sha
            self.repo = repo
        }
    }

    public init(id: Int, number: Int, url: String, head: Head, base: Base) {
        self.id = id
        self.number = number
        self.url = url
        self.head = head
        self.base = base
    }
}
