// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

/// Generated Release Notes Content
///
/// Generated name and body describing a release
public struct ReleaseNotesContent: Codable {
    /// The generated name of the release
    ///
    /// Example: "Release v1.0.0 is now available!"
    public var name: String
    /// The generated body describing the contents of the release supporting markdown formatting
    public var body: String

    public init(name: String, body: String) {
        self.name = name
        self.body = body
    }
}
