// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

public struct ReviewDismissedIssueEvent: Codable {
    public var id: Int
    public var nodeID: String
    public var url: String
    /// Simple User
    public var actor: SimpleUser
    public var event: String
    public var commitID: String?
    public var commitURL: String?
    public var createdAt: String
    /// GitHub app
    ///
    /// GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub.
    public var performedViaGithubApp: Integration?
    public var dismissedReview: DismissedReview

    public struct DismissedReview: Codable {
        public var state: String
        public var reviewID: Int
        public var dismissalMessage: String?
        public var dismissalCommitID: String?

        public init(state: String, reviewID: Int, dismissalMessage: String? = nil, dismissalCommitID: String? = nil) {
            self.state = state
            self.reviewID = reviewID
            self.dismissalMessage = dismissalMessage
            self.dismissalCommitID = dismissalCommitID
        }

        private enum CodingKeys: String, CodingKey {
            case state
            case reviewID = "review_id"
            case dismissalMessage = "dismissal_message"
            case dismissalCommitID = "dismissal_commit_id"
        }
    }

    public init(id: Int, nodeID: String, url: String, actor: SimpleUser, event: String, commitID: String? = nil, commitURL: String? = nil, createdAt: String, performedViaGithubApp: Integration? = nil, dismissedReview: DismissedReview) {
        self.id = id
        self.nodeID = nodeID
        self.url = url
        self.actor = actor
        self.event = event
        self.commitID = commitID
        self.commitURL = commitURL
        self.createdAt = createdAt
        self.performedViaGithubApp = performedViaGithubApp
        self.dismissedReview = dismissedReview
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case nodeID = "node_id"
        case url
        case actor
        case event
        case commitID = "commit_id"
        case commitURL = "commit_url"
        case createdAt = "created_at"
        case performedViaGithubApp = "performed_via_github_app"
        case dismissedReview = "dismissed_review"
    }
}
