// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import NaiveDate

/// Self hosted runners
///
/// A self hosted runner
public struct Runner: Codable {
    /// The id of the runner.
    public var id: Int
    /// The name of the runner.
    ///
    /// Example: "iMac"
    public var name: String
    /// The Operating System of the runner.
    ///
    /// Example: "macos"
    public var os: String
    /// The status of the runner.
    ///
    /// Example: "online"
    public var status: String
    public var isBusy: Bool
    public var labels: [RunnerLabel]

    public init(id: Int, name: String, os: String, status: String, isBusy: Bool, labels: [RunnerLabel]) {
        self.id = id
        self.name = name
        self.os = os
        self.status = status
        self.isBusy = isBusy
        self.labels = labels
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case name
        case os
        case status
        case isBusy = "busy"
        case labels
    }
}
