// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct ScimEnterpriseGroup: Codable {
    public var schemas: [String]
    public var id: String
    public var externalID: String?
    public var displayName: String?
    public var members: [Member]?
    public var meta: Meta?

    public struct Member: Codable {
        public var value: String?
        public var ref: String?
        public var display: String?

        public init(value: String? = nil, ref: String? = nil, display: String? = nil) {
            self.value = value
            self.ref = ref
            self.display = display
        }

        private enum CodingKeys: String, CodingKey {
            case value
            case ref = "$ref"
            case display
        }
    }

    public struct Meta: Codable {
        public var resourceType: String?
        public var created: String?
        public var lastModified: String?
        public var location: String?

        public init(resourceType: String? = nil, created: String? = nil, lastModified: String? = nil, location: String? = nil) {
            self.resourceType = resourceType
            self.created = created
            self.lastModified = lastModified
            self.location = location
        }
    }

    public init(schemas: [String], id: String, externalID: String? = nil, displayName: String? = nil, members: [Member]? = nil, meta: Meta? = nil) {
        self.schemas = schemas
        self.id = id
        self.externalID = externalID
        self.displayName = displayName
        self.members = members
        self.meta = meta
    }

    private enum CodingKeys: String, CodingKey {
        case schemas
        case id
        case externalID = "externalId"
        case displayName
        case members
        case meta
    }
}
