// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct ShortBlob: Codable {
    public var url: String
    public var sha: String

    public init(url: String, sha: String) {
        self.url = url
        self.sha = sha
    }
}
