// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct Tag: Codable {
    /// Example: "v0.1"
    public var name: String
    public var commit: Commit
    /// Example: "https://github.com/octocat/Hello-World/zipball/v0.1"
    public var zipballURL: URL
    /// Example: "https://github.com/octocat/Hello-World/tarball/v0.1"
    public var tarballURL: URL
    public var nodeID: String

    public struct Commit: Codable {
        public var sha: String
        public var url: URL

        public init(sha: String, url: URL) {
            self.sha = sha
            self.url = url
        }
    }

    public init(name: String, commit: Commit, zipballURL: URL, tarballURL: URL, nodeID: String) {
        self.name = name
        self.commit = commit
        self.zipballURL = zipballURL
        self.tarballURL = tarballURL
        self.nodeID = nodeID
    }

    private enum CodingKeys: String, CodingKey {
        case name
        case commit
        case zipballURL = "zipball_url"
        case tarballURL = "tarball_url"
        case nodeID = "node_id"
    }
}
