// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct TeamMembership: Codable {
    public var url: URL
    /// The role of the user in the team.
    ///
    /// Example: "member"
    public var role: Role
    /// The state of the user's membership in the team.
    public var state: State

    /// The role of the user in the team.
    ///
    /// Example: "member"
    public enum Role: String, Codable, CaseIterable {
        case member
        case maintainer
    }

    /// The state of the user's membership in the team.
    public enum State: String, Codable, CaseIterable {
        case active
        case pending
    }

    public init(url: URL, role: Role, state: State) {
        self.url = url
        self.role = role
        self.state = state
    }
}
